const customers = [
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },

  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Active",
  },
  {
    name: "John Doe",
    company: "ABC Inc.",
    phone: "123-456-7890",
    email: "john@example.com",
    country: "USA",
    status: "Inactive",
  },
  // can add new customers
];

export default customers;
